export const refs = {
  bestBooks: document.querySelector('.best-books-category'),
  categories: document.querySelector('.sidebar-categories'),
  allCategories: document.querySelector('.sidebar-all-categories'),
  categoryTitle: document.querySelector('.best-books-title'),
  loader: document.querySelector('.loader'),
  loader1: document.querySelector('.loader1'),
  scrollToEl: document.querySelector('.global-books-block'),
  modalWindow: document.querySelector('modal-window'),
  seeMoreBtn: document.querySelector('.best-books-category'),
  headerBtn: document.querySelector('.header-burger-btn'),
  headerIcon: document.querySelector('.header-burger-icon'),
  headerMenu: document.querySelector('.header-modal-menu'),
  burgerSvg: document.querySelector('#burger-svg'),
  headerToggle: document.querySelector('#headerToggle'),
  root: document.querySelector(':root'),
  btnToTop: document.querySelector('.to-top'),
  element: document.querySelectorAll('.header-navigation-list-item'),
  modalElement: document.querySelectorAll(
    '.header-modal-menu-navigation-list-item'
  ),
  svg: document.querySelector('.header-modal-menu-icon'),
  modalLinks: document.querySelectorAll('.header-modal-menu-link'),
  links: document.querySelectorAll('.header-link'),
  svg1: document.querySelector('.header-bucket-icon'),
  headerContainer: document.querySelector('.header-container'),
};
